import { createClient } from '@supabase/supabase-js'
import type { Database } from '../../types/supabase'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

/**
 * Anon-key Supabase client. RLS 정책이 적용된 쿼리에만 사용.
 * 서버 측 service-role 호출은 `lib/auth/admin-supabase.ts` 의 `createAdminClient()` 사용.
 *
 * Database 타입은 `types/supabase.ts` (auto-generated by `npm run gen:types`).
 * 스키마 변경 시 위 명령으로 재생성.
 */
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey)

export type {
  Database,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  Json,
} from '../../types/supabase'
