import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createAdminClient } from '@/lib/auth/admin-supabase'
import type { BlogPost, BlogPostReview, ReviewPerspectivePreset } from '@/lib/blog'
import BlogEditor from './BlogEditor'
import ReviewHistoryPanel from './ReviewHistoryPanel'
import ReviewPanel from './ReviewPanel'

export const dynamic = 'force-dynamic'

export default async function BlogEditPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const supabase = createAdminClient()

  const [{ data: post }, { data: reviews }, { data: savedPerspectives }] = await Promise.all([
    supabase
      .from('jimscanner_blog_posts')
      .select('*')
      .eq('slug', slug)
      .maybeSingle<BlogPost>(),
    supabase
      .from('jimscanner_blog_post_reviews')
      .select('*')
      .eq('post_slug', slug)
      .order('created_at', { ascending: false }),
    supabase
      .from('jimscanner_blog_review_perspectives')
      .select('id, name, created_at, created_by')
      .order('created_at', { ascending: false }),
  ])

  if (!post) notFound()

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Link href="/admin/blog" className="text-xs text-gray-500 hover:text-blue-600">
          ← 블로그 목록
        </Link>
        <Link
          href={`/blog/${post.slug}`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-sm text-blue-600 hover:underline"
        >
          프론트 미리보기 ↗
        </Link>
      </div>

      <ReviewHistoryPanel
        pipelineStatus={post.pipeline_status}
        revisionCount={post.revision_count}
        autoGenerated={post.auto_generated}
        reviewHistory={post.review_history}
        lastTickAt={post.last_pipeline_tick_at}
      />

      <ReviewPanel
        slug={post.slug}
        reviews={(reviews ?? []) as BlogPostReview[]}
        savedPerspectives={(savedPerspectives ?? []) as ReviewPerspectivePreset[]}
      />

      <BlogEditor key={post.updated_at} initial={post} />
    </div>
  )
}
