import type { ReviewEntry, PipelineStatus } from '@/lib/blog'
import { PIPELINE_STATUS_LABEL } from '@/lib/blog'

type Props = {
  pipelineStatus?: PipelineStatus
  revisionCount?: number
  autoGenerated?: boolean
  reviewHistory?: ReviewEntry[]
  lastTickAt?: string | null
}

function Score({ label, value }: { label: string; value?: number }) {
  if (value == null) return null
  const color =
    value >= 8 ? 'text-green-600' : value >= 5 ? 'text-amber-600' : 'text-red-600'
  return (
    <div className="flex-1 min-w-0 text-center">
      <div className={`text-2xl font-bold tabular-nums ${color}`}>{value}</div>
      <div className="text-[10px] uppercase tracking-wide text-gray-500">{label}</div>
    </div>
  )
}

function List({ title, items }: { title: string; items?: string[] }) {
  if (!items || items.length === 0) return null
  return (
    <div>
      <div className="text-xs font-semibold text-gray-700 mb-1">{title}</div>
      <ul className="list-disc list-inside space-y-0.5 text-xs text-gray-700">
        {items.map((it, i) => (
          <li key={i}>{it}</li>
        ))}
      </ul>
    </div>
  )
}

function overallBadge(overall: ReviewEntry['overall']) {
  if (overall === 'approve')
    return <span className="text-xs px-2 py-0.5 rounded bg-green-100 text-green-700 font-medium">approve</span>
  if (overall === 'needs_revision')
    return <span className="text-xs px-2 py-0.5 rounded bg-amber-100 text-amber-700 font-medium">needs_revision</span>
  return <span className="text-xs px-2 py-0.5 rounded bg-red-100 text-red-700 font-medium">reject</span>
}

export default function ReviewHistoryPanel({
  pipelineStatus,
  revisionCount,
  autoGenerated,
  reviewHistory,
  lastTickAt,
}: Props) {
  // 자동 생성되지 않은 수동 글은 아예 패널 숨김
  if (!autoGenerated) return null

  const statusMeta = pipelineStatus
    ? PIPELINE_STATUS_LABEL[pipelineStatus]
    : PIPELINE_STATUS_LABEL.manual

  const history = (reviewHistory ?? []).slice().reverse() // 최신이 위

  return (
    <section className="bg-white border rounded-lg p-5 space-y-4">
      <header className="flex items-start justify-between flex-wrap gap-2">
        <div>
          <h2 className="text-sm font-bold text-gray-900 flex items-center gap-2">
            🤖 파이프라인 검토 기록
          </h2>
          <p className="text-xs text-gray-500 mt-0.5">
            이 글은 자동 파이프라인에서 생성되었습니다. 게시 전에 반드시 팩트·문체를 검토·편집해 주세요.
          </p>
        </div>
        <div className="flex items-center gap-2 text-xs">
          <span className={`px-2 py-0.5 rounded font-medium ${statusMeta.color}`}>
            {statusMeta.label}
          </span>
          <span className="px-2 py-0.5 rounded bg-gray-100 text-gray-700 font-mono">
            rev {revisionCount ?? 0}
          </span>
          {lastTickAt && (
            <span className="text-gray-400">
              마지막 실행 {new Date(lastTickAt).toLocaleString('ko-KR', { dateStyle: 'short', timeStyle: 'short' })}
            </span>
          )}
        </div>
      </header>

      {history.length === 0 ? (
        <div className="text-xs text-gray-500 bg-gray-50 rounded px-3 py-2">
          아직 검토 기록이 없습니다. 다음 파이프라인 tick 에서 검토가 이루어질 예정입니다.
        </div>
      ) : (
        <div className="space-y-4">
          {history.map((r, idx) => (
            <details
              key={idx}
              open={idx === 0}
              className="border rounded-lg"
            >
              <summary className="cursor-pointer list-none px-4 py-3 hover:bg-gray-50 flex items-center justify-between gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <span className="text-xs font-mono text-gray-500 shrink-0">
                    #{history.length - idx}
                  </span>
                  {overallBadge(r.overall)}
                  <span className="text-xs text-gray-600 shrink-0">
                    rev {r.revision_count_at_review}
                  </span>
                  {r.scores && (
                    <span className="text-xs font-mono text-gray-700 shrink-0">
                      {r.scores.total}/50
                    </span>
                  )}
                  {r.one_line_summary && (
                    <span className="text-xs text-gray-600 truncate">
                      — {r.one_line_summary}
                    </span>
                  )}
                </div>
                <span className="text-[11px] text-gray-400 shrink-0">
                  {new Date(r.tick_at).toLocaleString('ko-KR', { dateStyle: 'short', timeStyle: 'short' })}
                </span>
              </summary>

              <div className="px-4 py-3 border-t space-y-4 bg-gray-50/50">
                {r.error && (
                  <div className="text-xs text-red-700 bg-red-50 border border-red-200 rounded px-3 py-2">
                    <strong>오류:</strong> {r.error}
                  </div>
                )}

                {r.scores && (
                  <div className="flex gap-2 bg-white border rounded-md p-3">
                    <Score label="SEO" value={r.scores.seo} />
                    <Score label="유입" value={r.scores.traffic_potential} />
                    <Score label="CTR" value={r.scores.ctr_potential} />
                    <Score label="팩트" value={r.scores.facts} />
                    <Score label="사람 같음" value={r.scores.human_likeness} />
                  </div>
                )}

                <div className="grid sm:grid-cols-2 gap-4">
                  {r.seo && (
                    <div className="space-y-2">
                      <div className="text-xs font-semibold text-gray-900">📈 SEO</div>
                      <List title="이슈" items={r.seo.issues} />
                      <List title="개선 제안" items={r.seo.suggestions} />
                    </div>
                  )}

                  {r.traffic_potential && (
                    <div className="space-y-2">
                      <div className="text-xs font-semibold text-gray-900">🎯 유입 잠재력</div>
                      {r.traffic_potential.target_keywords &&
                        r.traffic_potential.target_keywords.length > 0 && (
                          <div className="flex flex-wrap gap-1">
                            {r.traffic_potential.target_keywords.map((k, i) => (
                              <span
                                key={i}
                                className="text-[11px] px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-100"
                              >
                                {k}
                              </span>
                            ))}
                          </div>
                        )}
                      <div className="text-[11px] text-gray-600 space-x-3">
                        {r.traffic_potential.estimated_monthly_volume_tier && (
                          <span>볼륨: <strong>{r.traffic_potential.estimated_monthly_volume_tier}</strong></span>
                        )}
                        {r.traffic_potential.cannibalization_risk && (
                          <span>카니발: <strong>{r.traffic_potential.cannibalization_risk}</strong></span>
                        )}
                      </div>
                      <List title="이슈" items={r.traffic_potential.issues} />
                      <List title="개선 제안" items={r.traffic_potential.suggestions} />
                    </div>
                  )}

                  {r.ctr_potential && (
                    <div className="space-y-2">
                      <div className="text-xs font-semibold text-gray-900">🖱️ 클릭 잠재력</div>
                      {r.ctr_potential.title_review && (
                        <div className="text-xs text-gray-700">
                          <strong>제목 평:</strong> {r.ctr_potential.title_review}
                        </div>
                      )}
                      {r.ctr_potential.excerpt_review && (
                        <div className="text-xs text-gray-700">
                          <strong>excerpt 평:</strong> {r.ctr_potential.excerpt_review}
                        </div>
                      )}
                      <List title="개선 제안" items={r.ctr_potential.suggestions} />
                    </div>
                  )}

                  {r.facts && (
                    <div className="space-y-2">
                      <div className="text-xs font-semibold text-gray-900">✅ 팩트 정확성</div>
                      <List title="검증 완료" items={r.facts.verified_claims} />
                      {r.facts.incorrect_claims && r.facts.incorrect_claims.length > 0 && (
                        <div>
                          <div className="text-xs font-semibold text-red-700 mb-1">잘못된 주장</div>
                          <ul className="text-xs text-red-700 space-y-1">
                            {r.facts.incorrect_claims.map((c, i) => (
                              <li key={i} className="bg-red-50 border border-red-200 rounded px-2 py-1">
                                <span className="line-through">{c.quote}</span>
                                <span className="text-gray-700"> → {c.correct_value}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      <List title="개선 제안" items={r.facts.suggestions} />
                    </div>
                  )}

                  {r.human_likeness && (
                    <div className="space-y-2 sm:col-span-2">
                      <div className="text-xs font-semibold text-gray-900">🧑 AI 스럽지 않은가</div>
                      <List title="발견된 AI 패턴" items={r.human_likeness.ai_patterns_found} />
                      <List title="개선 제안" items={r.human_likeness.suggestions} />
                    </div>
                  )}
                </div>
              </div>
            </details>
          ))}
        </div>
      )}
    </section>
  )
}
